### ISSUE TITLE
Sea3D Studio

### ISSUE THREAD

**Issue by DezEbuwa** [sunag/sea3d_studio_sdk#1]
An issue I am running into is that flash player crashes whenever I have file that contains a lot of animation frames. The one I am currently working with has about 7000 frames. All mocap. Is there a way to edit the file without using the web based editor? What is the limit for animation frames when using sea3d studio?

Should I be asking this question in issues?

**Comment by sunag** [comment]
Hi @DezEbuwa 

I will be answering in the forum, the forum not notifying me. 
Thanks!

http://community.poonya.com/151
